################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

---

name: Setup appimagetool

description: |
  To setup appimagetool, its runtimes and static tools.
  As a result, the 'FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE' environment variable contains the full name of the appimagetool-x86_64.AppImage file,
  the 'PATH' and 'FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR' environment variable contains the full path of the appimagetool-x86_64.AppImage directory.
  Look at - https://github.com/AppImage/appimagetool;
            https://github.com/AppImage/type2-runtime;
            https://github.com/probonopd/static-tools;
            https://github.com/AppImage/AppImageKit#appimagetool-usage;

runs:
  using: "composite"

  steps:
    - name: Check conditions
      shell: bash
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          echo "::error::This action only supports Linux (Now it runs on $RUNNER_OS)."
          exit 1
        fi

    - name: Prepare to setup the appimagetool
      id: prepare-appimagetool
      shell: bash
      run: |
        appimagetool_dir="./.appimagetool/$(uuidgen)"
        mkdir -p "$appimagetool_dir"

        appimagetool_dir=$(readlink -f "$(pwd)/$dir")
        echo "$appimagetool_dir" >> $GITHUB_PATH
        echo "directory=$appimagetool_dir" >> $GITHUB_OUTPUT

    - name: Setup appimagetool
      id: setup-appimagetool
      shell: bash
      run: |
        url="https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
        appimagetool_dir="${{ steps.prepare-appimagetool.outputs.directory }}"
        appimagetool_file="$appimagetool_dir/appimagetool-x86_64.AppImage"

        echo "Download appimagetool to '$appimagetool_dir'"
        wget --quiet --output-document="$appimagetool_file" "$url"

        echo "Setup appimagetool: $appimagetool_file"
        chmod a+x "$appimagetool_file"

        echo "FINEBITS_GITHUB_ACTION_APPIMAGETOOL_DIR=$appimagetool_dir" >> $GITHUB_ENV
        echo "FINEBITS_GITHUB_ACTION_APPIMAGETOOL_FILE=$appimagetool_file" >> $GITHUB_ENV

    - name: Setup Runtimes
      shell: bash
      run: |
        urls=("https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64"
              "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-aarch64"
              "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-armhf"
              "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-i686")
        appimagetool_dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        echo "Downloading runtimes..."

        for url in "${urls[@]}"
        do
          name="${url##*/}"
          file="$appimagetool_dir/$name"
          wget --quiet --output-document="$file" "$url"
        done

    - name: Setup Static Tools
      shell: bash
      run: |
        urls=("https://github.com/probonopd/static-tools/releases/download/continuous/appstreamcli-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/bsdtar-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/desktop-file-install-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/desktop-file-validate-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/mksquashfs-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/patchelf-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/unsquashfs-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/update-desktop-database-x86_64"
              "https://github.com/probonopd/static-tools/releases/download/continuous/zsyncmake-x86_64")
        appimagetool_dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        echo "Downloading static tools..."

        for url in "${urls[@]}"
        do
          name="${url##*/}"
          name="${name%-*}"
          file="$appimagetool_dir/$name"
          wget --quiet --output-document="$file" "$url"
          chmod a+x "$file"
        done
