################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Setup appimagetool

description: | 
  To setup appimagetool and its runtimes. Look at - https://github.com/AppImage/AppImageKit#appimagetool-usage
  As a result, the 'GITHUB_ACTION_APPIMAGETOOL_FILE' environment variable contains the full name of the appimagetool-x86_64.AppImage file
  and the 'GITHUB_ACTION_APPIMAGETOOL_DIR' environment variable contains the full path of the appimagetool-x86_64.AppImage directory

inputs:
  appimagetool-runtime:
    description: 'To setup additional runtimes'
    type: choice
    options:
    - all
    - aarch64
    - armhf
    - i686
    - x86_64
    - none
    required: false
    default: all

runs:
  using: "composite"

  steps:
    - name: Check conditions
      shell: bash
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          echo "::error::This action only supports Linux (Now it runs on $RUNNER_OS)."
          exit 1
        fi

    - name: Prepare to setup the appimagetool
      id: prepare-appimagetool
      shell: bash
      run: |
        appimagetool_dir="./.appimagetool/$(uuidgen)"
        mkdir -p "$appimagetool_dir"

        echo "directory=$appimagetool_dir" >> $GITHUB_OUTPUT

    - name: Setup appimagetool
      id: setup-appimagetool
      shell: bash
      run: |
        echo "Install libfuse2"
        sudo add-apt-repository universe && sudo apt install libfuse2

        url="https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        echo "Download appimagetool to '$(pwd)/$dir'"
        wget --quiet --directory-prefix="$dir" "$url"

        appimagetool=$(find . -path "$dir/appimagetool-*.AppImage" -print | head -n 1)

        appimagetool_file=$(readlink -f "$appimagetool")
        echo "Setup appimagetool: $appimagetool_file"
        chmod a+x "$appimagetool_file"

        appimagetool_dir=$(readlink -f "$(pwd)/$dir")

        echo "GITHUB_ACTION_APPIMAGETOOL_DIR=$appimagetool_dir" >> $GITHUB_ENV
        echo "GITHUB_ACTION_APPIMAGETOOL_FILE=$appimagetool_file" >> $GITHUB_ENV

    - name: Setup x86_64 Runtime
      if: inputs.appimagetool-runtime == 'x86_64' || inputs.appimagetool-runtime == 'all' 
      shell: bash
      run: |
        url="https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64"
        dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        wget --quiet --directory-prefix="$dir" "$url"

    - name: Setup aarch64 Runtime
      if: inputs.appimagetool-runtime == 'aarch64' || inputs.appimagetool-runtime == 'all' 
      shell: bash
      run: |
        url="https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-aarch64"
        dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        wget --quiet --directory-prefix="$dir" "$url"

    - name: Setup i686 (i383) Runtime
      if: inputs.appimagetool-runtime == 'i686' || inputs.appimagetool-runtime == 'all' 
      shell: bash
      run: |
        url="https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-i686"
        dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        wget --quiet --directory-prefix="$dir" "$url"

    - name: Setup armhf Runtime
      if: inputs.appimagetool-runtime == 'armhf' || inputs.appimagetool-runtime == 'all' 
      shell: bash
      run: |
        url="https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-armhf"
        dir="${{ steps.prepare-appimagetool.outputs.directory }}"

        wget --quiet --directory-prefix="$dir" "$url"
