################################################################################
#                                                                              #
#   Copyright 2023 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Version Number

description: It finds out the current version number

outputs:
  major:
    value: ${{ steps.tag-version.outputs.major }}
  minor:
    value: ${{ steps.tag-version.outputs.minor }}
  patch:
    value: ${{ steps.tag-version.outputs.patch }}
  build:
    value: ${{ steps.action-context.outputs.build }}
  attempt:
    value: ${{ steps.action-context.outputs.attempt }}
  today:
    value: ${{ steps.action-context.outputs.today }}
  githash:
    value: ${{ steps.commit.outputs.githash }}
  suffix:
    value: ${{ steps.tag-version.outputs.suffix }}
  preset-build:
    value: ${{ steps.preset.outputs.build-version }}
  preset-suffix:
    value: ${{ steps.preset.outputs.suffix-version }}
  preset-semantic-1: # https://semver.org/spec/v1.0.0.html
    value: ${{ steps.preset.outputs.semantic-1-version }}
  preset-semantic-2: # https://semver.org/spec/v2.0.0.html
    value: ${{ steps.preset.outputs.semantic-2-version }}
  preset-build-githash:
    value: ${{ steps.preset.outputs.build-githash-version }}
  preset-suffix-githash:
    value: ${{ steps.preset.outputs.suffix-githash-version }}
  preset-semantic-2-githash: # https://semver.org/spec/v2.0.0.html
    value: ${{ steps.preset.outputs.semantic-2-githash-version }}
runs:
  using: "composite"

  steps:
    - id: tag-version
      shell: bash
      run: |
        regex="v([0-9]+)\.?([0-9]*)\.?([0-9]*)[^a-zA-Z]?(.*)"
        version=$(git describe --tags --abbrev=0 --match "v[0-9]*" --always)

        echo "tag: $version"

        if [[ $version =~ $regex ]]; then
          major=${BASH_REMATCH[1]}
          minor=${BASH_REMATCH[2]}
          patch=${BASH_REMATCH[3]}
          suffix=${BASH_REMATCH[4]}
        else
          major=0
          minor=1
        fi

        echo "major=$([[ -z $major ]] && echo 1 || echo $major)" >> $GITHUB_OUTPUT
        echo "minor=$([[ -z $minor ]] && echo 0 || echo $minor)" >> $GITHUB_OUTPUT
        echo "patch=$([[ -z $patch ]] && echo 0 || echo $patch)" >> $GITHUB_OUTPUT
        echo "suffix=$([[ -z $suffix ]] && echo '' || echo ${suffix##*(-)})" >> $GITHUB_OUTPUT

    - id: commit
      shell: bash
      run: |
        echo "githash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - id: action-context
      shell: bash
      run: |
        echo "today=$(date -u "+%y%m%d")" >> $GITHUB_OUTPUT
        echo "build=${{ github.run_number }}" >> $GITHUB_OUTPUT
        echo "attempt=${{ github.run_attempt }}" >> $GITHUB_OUTPUT

    - id: preset
      shell: bash
      run: |
        suffix=${{ env.suffix }}
        suffix=$([[ -z $suffix ]] && echo '' || echo "-$suffix")

        buildversion=${{ env.major }}.${{ env.minor }}.${{ env.patch }}.${{ env.build }}
        echo "build-version=$(echo $buildversion )" >> $GITHUB_OUTPUT
        echo "build-githash-version=$(echo $buildversion+${{ env.githash }} )" >> $GITHUB_OUTPUT

        suffixversion=${{ env.major }}.${{ env.minor }}.${{ env.patch }}.${{ env.build }}$suffix
        echo "suffix-version=$(echo $suffixversion )" >> $GITHUB_OUTPUT
        echo "suffix-githash-version=$(echo $suffixversion+${{ env.githash }} )" >> $GITHUB_OUTPUT

        semanticversion1=${{ env.major }}.${{ env.minor }}.${{ env.patch }}$suffix
        echo "semantic-1-version=$(echo $semanticversion1 )" >> $GITHUB_OUTPUT

        semanticversion2=${{ env.major }}.${{ env.minor }}.${{ env.patch }}$suffix+${{ env.build }}.${{ env.attempt }}
        echo "semantic-2-version=$(echo $semanticversion2 )" >> $GITHUB_OUTPUT
        echo "semantic-2-githash-version=$(echo $semanticversion2.${{ env.githash }} )" >> $GITHUB_OUTPUT

      env:
        major: ${{ steps.tag-version.outputs.major }}
        minor: ${{ steps.tag-version.outputs.minor }}
        patch: ${{ steps.tag-version.outputs.patch }}
        build: ${{ steps.action-context.outputs.build }}
        today: ${{ steps.action-context.outputs.today }}
        attempt: ${{ steps.action-context.outputs.attempt }}
        githash: ${{ steps.commit.outputs.githash }}
        suffix: ${{ steps.tag-version.outputs.suffix }}
