################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

name: Select Configuration

description: To select a configuration by keywords.

inputs:
  json:
    description: 'JSON data'
    type: string

  json-file:
    description: 'Path to JSON file'
    type: string

  keywords:
    description: 'A set of keywords separated by the "," symbol'
    type: string
    required: true

  configs-set-jsonpath:
    description: 'JSON path to the configuration set, where "." is the JSON root'
    type: string
    default: '.'
   
  keywords-set-jsonpath:
    description: 'JSON path to a set of keys, where "." is the configuration root'
    type: string
    default: '.keywords'

  exclude-keywords:
    description: 'It excludes keywords from the output JSON configurations'
    type: boolean
    default: true

outputs:
  config-json:
    value: ${{ steps.select-config.outputs.config }}
  matrix:
    value: ${{ steps.select-config.outputs.matrix }}

runs:
  using: "composite"

  steps:

  - name: verify
    shell: bash
    run: |
      [[ '${{ inputs.json }}' || '${{ inputs.json-file }}' ]] || { echo "::error::Input parameters "json" and "json-file" are empty." ; exit 1; }
      [[ '${{ inputs.keywords }}' ]] || { echo "::error::Input parameter "keywords" is empty." ; exit 1; }

  - id: select-config
    shell: bash
    run: | 
      json='${{ inputs.json }}'
      json_file='${{ inputs.json-file }}'
      keywords='${{ inputs.keywords }}'
      configs_path='${{ inputs.configs-set-jsonpath }}'
      keyset_path='${{ inputs.keywords-set-jsonpath }}'
      exclude_keys='${{ inputs.exclude-keywords }}'
      compact_output='${{ inputs.compact-output }}'

      query="(\"$keywords\"/\",\") as \$keys | [ $configs_path[] | ($keyset_path) as \$keyset | select(all(\$keys[]; IN(\$keyset[]))) $("$exclude_keys" && echo "| del($keyset_path)") ]"
      echo "query: $query"

      config=""
      if [[ "$json" ]]; then
        config=$( echo "$json" | jq -r -c "$query")
      else
        config=$( jq -r -c "$query" "$json_file" )
      fi

      echo "config: $config"

      echo "config=$config" >> $GITHUB_OUTPUT
      echo "matrix={\"include\":$config}" >> $GITHUB_OUTPUT
