################################################################################
#                                                                              #
#   Copyright 2024-2026 Finebits (https://finebits.com)                        #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

---

name: Read the Uno Platform setup manifest

description: |
  Read the Uno Platform setup manifest from the 'uno-check' tool
  Prerequisites: .NET SDK

inputs:
  uno-check-manifest:
    type: string
    description: Specific manifest URL of the 'uno-check' tool
    default: ''
    required: false

  uno-check-version:
    type: string
    description: Specific version of the 'uno-check' tool
    default: ''
    required: false

outputs:
  content:
    value: ${{ steps.read-manifest.outputs.content }}

runs:
  using: "composite"

  steps:
    - id: uno-check-version-manifest
      if: inputs.uno-check-manifest == ''
      shell: bash
      run: |
        version="${{ inputs.uno-check-version }}"

        if [[ -z $version ]]; then
          info=($(echo "$(dotnet tool search "uno.check unoplatform")" | echo $(grep "uno.check")))
          version=$([[ "${info[0]}" = "uno.check" ]] && echo "${info[1]}" || echo "")
        fi

        if [[ -z $version ]]; then
          echo "::error::uno.check tool version not found."
        fi

        url="https://raw.githubusercontent.com/unoplatform/uno.check/refs/tags/${version}/manifests/uno.ui.manifest.json"
        echo "url=$url" >> $GITHUB_OUTPUT

    - id: manifest-url
      shell: bash
      run: |
        input_url="${{ inputs.uno-check-manifest }}"
        version_url="${{ steps.uno-check-version-manifest.outputs.url }}"

        url="${input_url:-$version_url}"
        echo "url=$url" >> $GITHUB_OUTPUT

    - id: read-manifest
      uses: finebits/github-actions/toolset/file/read@v3.0.1
      with:
        url: ${{ steps.manifest-url.outputs.url }}
