################################################################################
#                                                                              #
#   Copyright 2024 Finebits (https://finebits.com)                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
################################################################################

---

name: Check the 'toolset/find-out-version' Action

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:

jobs:

  checks:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Run 'toolset/find-out-version' action
        id: version-number
        uses: ./toolset/find-out-version

      - name: Check 'toolset/find-out-version' action
        shell: bash
        run: |
          regex_number="^[0-9]+$"

          major="${{ steps.version-number.outputs.major }}"
          echo "Major: $major"
          if [[ ! $major =~  $regex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'major' output is incorrect."
            exit 1
          fi

          minor="${{ steps.version-number.outputs.minor }}"
          echo "Minor: $minor"
          if [[ ! $minor =~  $regex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'minor' output is incorrect."
            exit 1
          fi

          patch="${{ steps.version-number.outputs.patch }}"
          echo "Patch: $patch"
          if [[ ! $patch =~  $regex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'patch' output is incorrect."
            exit 1
          fi

          build="${{ steps.version-number.outputs.build }}"
          echo "Build: $build"
          if [[ ! $build =~  $regex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'build' output is incorrect."
            exit 1
          fi

          attempt="${{ steps.version-number.outputs.attempt }}"
          echo "Attempt: $attempt"
          if [[ ! $attempt =~  $regex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'attempt' output is incorrect."
            exit 1
          fi

          today="${{ steps.version-number.outputs.today }}"
          echo "Today: $today"
          if [[ ! $today =~  $regex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'today' output is incorrect."
            exit 1
          fi

          regex_hex_number="^[0-9a-fA-F]+$"
          githash="${{ steps.version-number.outputs.githash }}"
          echo "Git hash: $githash"
          if [[ ! $githash =~  $regex_hex_number ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'githash' output is incorrect."
            exit 1
          fi

          regex_suffix="^[a-zA-Z0-9\.-]?$"
          suffix="${{ steps.version-number.outputs.suffix }}"
          echo "Suffix: $suffix"
          if [[ ! $suffix =~  $regex_suffix ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'suffix' output is incorrect."
            exit 1
          fi

          preset_build_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$"
          preset_build="${{ steps.version-number.outputs.preset-build }}"
          echo "Preset Build version: $preset_build"
          if [[ ! $preset_build =~ $preset_build_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build' output is incorrect."
            exit 1
          fi

          preset_suffix_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?$"
          preset_suffix="${{ steps.version-number.outputs.preset-suffix }}"
          echo "Preset Suffix version: $preset_suffix"
          if [[ ! $preset_suffix =~ $preset_suffix_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix' output is incorrect."
            exit 1
          fi

          preset_semantic_1_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$"
          preset_semantic_1="${{ steps.version-number.outputs.preset-semantic-1 }}"
          echo "Preset Semantic version 1.0: $preset_semantic_1"
          if [[ ! $preset_semantic_1 =~ $preset_semantic_1_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-1' output is incorrect."
            exit 1
          fi

          preset_semantic_2_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?(\+[a-zA-Z0-9\.-]+)?$"
          preset_semantic_2="${{ steps.version-number.outputs.preset-semantic-2 }}"
          echo "Preset Semantic version 2.0: $preset_semantic_2"
          if [[ ! $preset_semantic_2 =~ $preset_semantic_2_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2' output is incorrect."
            exit 1
          fi

          preset_build_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\+[0-9a-fA-F]+$"
          preset_build_githash="${{ steps.version-number.outputs.preset-build-githash }}"
          echo "Preset Build version with githash: $preset_build_githash"
          if [[ ! $preset_build_githash =~ $preset_build_githash_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-build-githash' output is incorrect."
            exit 1
          fi

          preset_suffix_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+[0-9a-fA-F]+$"
          preset_suffix_githash="${{ steps.version-number.outputs.preset-suffix-githash }}"
          echo "Preset Suffix version with githash: $preset_suffix_githash"
          if [[ ! $preset_suffix_githash =~ $preset_suffix_githash_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-suffix-githash' output is incorrect."
            exit 1
          fi

          preset_semantic_2_githash_regex="^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9\.-]+)?\+([a-zA-Z0-9\.-]+\.)?[0-9a-fA-F]+$"
          preset_semantic_2_githash="${{ steps.version-number.outputs.preset-semantic-2-githash }}"
          echo "Preset Semantic version 2.0 with githash: $preset_semantic_2_githash"
          if [[ ! $preset_semantic_2_githash =~ $preset_semantic_2_githash_regex ]]; then
            echo "::error::The 'toolset/find-out-version' action failed the tests. The 'preset-semantic-2-githash' output is incorrect."
            exit 1
          fi
